<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\CutLocal.Application\CutLocal.Application.csproj" />
    <ProjectReference Include="..\..\src\CutLocal.App\CutLocal.App.csproj" />
    <ProjectReference Include="..\..\src\CutLocal.Domain\CutLocal.Domain.csproj" />
    <ProjectReference Include="..\..\src\CutLocal.Imaging\CutLocal.Imaging.csproj" />
    <ProjectReference Include="..\..\src\CutLocal.Inference\CutLocal.Inference.csproj" />
    <ProjectReference Include="..\..\src\CutLocal.Persistence\CutLocal.Persistence.csproj" />
  </ItemGroup>
</Project>
