changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
  categories:
    - title: Added
      labels:
        - enhancement
        - feature
    - title: Fixed
      labels:
        - bug
        - fix
    - title: Documentation and maintenance
      labels:
        - documentation
        - dependencies
        - maintenance
    - title: Other changes
      labels:
        - "*"
